# Pandas Day 6 – GroupBy & Aggregation

## Why do we use groupby()?

### Definition
`groupby()` is used to split data into groups based on one or more column values so you can perform calculations on each group separately.

### Syntax
```python
df.groupby("ColumnName")
```

In [2]:
# step 1 we need to import pandas library
import pandas as pd

# Dataset
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Ravi", "Priya", "Arjun", "Kiran"],
    "Department": ["IT", "HR", "IT", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 90000, 75000],
    "Age": [25, 27, 30, 26, 32, 29]
}

df = pd.DataFrame(data)
print('Dataset'.center(35,'-'))
print(df)
print('-'* 35)

--------------Dataset--------------
    Name Department  Salary  Age
0    Ram         IT   70000   25
1   Sita         HR   50000   27
2   Ravi         IT   80000   30
3  Priya         HR   60000   26
4  Arjun    Finance   90000   32
5  Kiran         IT   75000   29
-----------------------------------

In [7]:
print(df.groupby('Department'))

# df.groupby("Department") by itself does not calculate anything, so Jupyter shows the groupby object like <pandas.core.groupby.generic.DataFrameGroupBy object ...>.
# Why it happens
# groupby() only creates grouped data internally. It becomes useful only when you add an aggregation like .mean(), .sum(), .max(), .count(), or .size().

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x106bbd0d0>

In [ ]:
# now we perform group by operations
print(df.groupby('Department')['Salary'].max())

In [11]:
# Find the average salary for each department.
print('Average Calculation'.center(35,'-'))
print(df.groupby('Department')['Salary'].mean())
print('-' * 35)

--------Average Calculation--------
Department
Finance    90000.0
HR         55000.0
IT         75000.0
Name: Salary, dtype: float64
-----------------------------------

In [13]:
# Find the maximum salary for each department.
print('Maximum Salary Calculation'.center(35,'-'))
print(df.groupby('Department')['Salary'].max())
print('-' * 35)

-----Maximum Salary Calculation----
Department
Finance    90000
HR         60000
IT         80000
Name: Salary, dtype: int64
-----------------------------------

In [14]:
# Find the minimum salary for each department.
print('Minimum Salary Calculation'.center(35,'-'))
print(df.groupby('Department')['Salary'].min())
print('-' * 35)

-----Minimum Salary Calculation----
Department
Finance    90000
HR         50000
IT         70000
Name: Salary, dtype: int64
-----------------------------------

In [15]:
# Find the total salary for each department.
print('Total Salary Calculation'.center(35,'-'))
print(df.groupby('Department')['Salary'].sum())
print('-' * 35)

------Total Salary Calculation-----
Department
Finance     90000
HR         110000
IT         225000
Name: Salary, dtype: int64
-----------------------------------

In [17]:
# Count how many employees are in each department.
print('Dep Wise Emp_Count'.center(35,'-'))
print(df.groupby('Department').size())
print('-' * 35)

---------Dep Wise Emp_Count--------
Department
Finance    1
HR         2
IT         3
dtype: int64
-----------------------------------

In [28]:
# Show salary statistics using agg() with count, sum, mean, min, and max.
print('showing salary statistics'.center(50,'-'))
print(df.groupby('Department')['Salary'].agg(['count','sum','mean','min','max']))
print('-' * 50)

------------showing salary statistics-------------
            count     sum     mean    min    max
Department
Finance         1   90000  90000.0  90000  90000
HR              2  110000  55000.0  50000  60000
IT              3  225000  75000.0  70000  80000
--------------------------------------------------

In [32]:
# Group by both Department and Age, then find the average salary.
print('Average Calacultion For Dep and Age with salary')
print(df.groupby(['Department','Age'])['Salary'].mean())

Average Calacultion For Dep and Age with salary
Department  Age
Finance     32     90000.0
HR          26     60000.0
            27     50000.0
IT          25     70000.0
            29     75000.0
            30     80000.0
Name: Salary, dtype: float64

In [37]:
# Reset the index after grouping by department.
df.groupby('Department')['Salary'].mean().reset_index()

  Department   Salary
0    Finance  90000.0
1         HR  55000.0
2         IT  75000.0

## Reset the index after grouping by department

### Definition
`reset_index()` converts the grouped result back into a normal DataFrame.

### Syntax
```python
df.groupby("Department")["Salary"].mean().reset_index()
```

### Example
This gives the average salary of each department in table form.

In [70]:
# Compare count() and size() on the department column.
df.groupby('Department').count() # count counts all non null values

            Name  Salary  Age
Department
Finance        1       1    1
HR             2       2    2
IT             3       3    3

In [46]:
df.groupby('Department').size() # size counts the total no.of departments in each departments it counts null values also

Department
Finance    1
HR         2
IT         3
dtype: int64

## count() vs size() in groupby

### Definition

- `count()` counts only non-null values in the specified column for each group.  
- `size()` counts all rows in each group, including rows where values are null.

### Syntax

```python
df.groupby("Department")["Name"].count()   # counts non-null names
df.groupby("Department").size()            # counts all rows
```

### Difference between count() and size()

| Aspect                    | count()                                                                 | size()                                                              |
|---------------------------|-------------------------------------------------------------------------|---------------------------------------------------------------------|
| What it counts            | Non-null values in the selected column                                 | All rows in each group                                              |
| Needs a column selection? | Yes, usually used like `["col"].count()`                               | No, used directly on the groupby object                             |
| Affected by NaN values?   | Yes, ignores rows where the selected column is NaN                     | No, includes rows even if columns have NaN                          |
| Typical use case          | When you want to know how many valid (non-missing) entries a column has per group | When you want the total group size regardless of missing values     |

### Example (conceptual)

If a department has 3 rows but 1 row has `Name = NaN`:

- `df.groupby("Department")["Name"].count()` → 2  
- `df.groupby("Department").size()` → 3

In [59]:
# Filter only departments where average salary is greater than 70000.
[df.groupby("Department")["Salary"].mean() > 70000]

# or
avg_salary = df.groupby("Department")["Salary"].mean().reset_index()
avg_salary[avg_salary["Salary"] > 70000]

  Department   Salary
0    Finance  90000.0
2         IT  75000.0

In [65]:
df.groupby("Department")["Salary"].mean().reset_index()

  Department   Salary
0    Finance  90000.0
1         HR  55000.0
2         IT  75000.0

### Why do we use reset_index() after groupby?

When we use `groupby()`, the grouped column (here, `Department`) becomes the index of the result instead of a normal column.  
`reset_index()` converts that index back into a regular column so the output becomes a clean DataFrame, making it easier to filter, sort, and work with column names like `"Department"` and `"Salary"`.

```python
avg_salary = df.groupby("Department")["Salary"].mean().reset_index()
avg_salary[avg_salary["Salary"] > 70000]
```

## Rapid Fire: Pandas groupby & aggregation

### 1. What does `groupby()` do in pandas?

It splits the DataFrame into groups based on one or more columns so you can apply functions (like `mean`, `sum`) to each group separately.

---

### 2. Does `groupby()` alone calculate anything?

No. `groupby()` alone just creates a GroupBy object; you must add an aggregation or transformation (like `.mean()`, `.sum()`) to get results.

---

### 3. Write basic syntax to group by a column and get average salary.

```python
df.groupby("Department")["Salary"].mean()
```

---

### 4. How do you get count, sum, mean, min, max of salary per department in one line?

```python
df.groupby("Department")["Salary"].agg(["count", "sum", "mean", "min", "max"])
```

---

### 5. What is the difference between `count()` and `size()` in groupby?

- `count()` counts only non-null values in the selected column.  
- `size()` counts all rows in each group, including NaN.

---

### 6. Write syntax to count employees per department using both.

```python
df.groupby("Department")["Name"].count()  # non-null names
df.groupby("Department").size()          # all rows
```

---

### 7. How do you group by multiple columns?

```python
df.groupby(["Department", "Age"])["Salary"].mean()
```

---

### 8. Why do we use `reset_index()` after `groupby()`?

Because `groupby()` puts the grouping columns into the index; `reset_index()` converts them back into normal columns, making the result easier to read and filter.

---

### 9. Show syntax: average salary per department, as a clean DataFrame.

```python
avg_salary = df.groupby("Department")["Salary"].mean().reset_index()
```

---

### 10. How do you filter only departments where average salary > 70000?

```python
avg_salary = df.groupby("Department")["Salary"].mean().reset_index()
avg_salary[avg_salary["Salary"] > 70000]
```

---

### 11. How do you get the maximum salary in each department?

```python
df.groupby("Department")["Salary"].max()
```

---

### 12. How do you get the total salary per department?

```python
df.groupby("Department")["Salary"].sum()
```

---

### 13. In one line, how would you describe `groupby()`?

`groupby()` implements the split-apply-combine pattern: it splits data into groups, applies a function to each group, and combines the results into a new structure.

---

### 14. SQL vs pandas: How do you map `GROUP BY department, AVG(salary)`?

- SQL:  
  `SELECT department, AVG(salary) FROM table GROUP BY department;`  

- Pandas:  
  ```python
  df.groupby("Department")["Salary"].mean()
  ```

---

### 15. How to get number of rows per group as a DataFrame with a column name `count`?

```python
df.groupby("Department").size().reset_index(name="count")
```

In [66]:
df.groupby("Department").size().reset_index(name="count")

  Department  count
0    Finance      1
1         HR      2
2         IT      3